                    #HOSPITALS LIST
""" DISPLAYS THE LIST OF HOSPITALS TO BE CHOSEN FROM """

def Ariyamangalam():
    Lm=["1.JOSEPH EYE HOSPITAL, MELAPUDUR", "2.APOLLO SPECIALITY HOSPITAL"]
    for i in Lm:
        print(i)
    hno=int(input("Enter the hospital no. chosen"))
    return(Lm[hno-1])
def Abishekapuram():
    La=["1.TRICHY MEDICAL SERVICES","2.KAVERY MEDICAL CENTRE AND HOSPITAL", "3. A.J.HOSPITAL","4.JEYAM MULTISPECIALITY HOSPITAL","5.AMRISH ONCOLOGY","6.GITANJALI MEDICAL CENTRE","7.DR.G.VISWANATHAN SPECIALITY HOSPITALS","8.SMS HOSPITAL","9.STAR KIMS HOSPITALS","10.AIYSHWARIYA HOSPITAL","11.TRICHY SRM MEDICAL COLLEGE HOSPITAL AND RESEARCH CENTRE","12.VASAN EYE CARE","13.APOLLO HOSPITALS","14.MANGALAM HOSPITAL","15.SUGAM HOSPITAL","16.DAYAL NURSING HOME","17.SUNDARAM HOSPITAL","18. C.S.I. MISSION HOSPITAL","19.CETHAR HOSPITAL","20.ANANTHGIRI NURSING HOME","21.RETNA GLOBAL HOSPITAL","22.Q MED HOSPITAL","23.A G EYE HOSPITAL","24.ROYAL PEARL HOSPITAL","25.ATHREYA RETINAL CENTER","26.RATHNA MEDICAL CENTRE","27.KMC SPECIALITY","28.DEEPAN NURSING HOME","29.HARSHAMITRA SUPER SPECIALITY CANCER CENTRE"]
    for i in La:
        print(i)
    hno=int(input("Enter the hospital no. chosen"))
    return La[hno-1])

def Srirangam():
    Ls=["1.G V N HOSPITAL PVT LTD","2.ATLAS HOSPITAL","3.FRONTLINE HOSPITAL"]
    for i in Ls:
        print(i)
    hno=int(input("Enter the hospital no. chosen"))
    return(Ls[hno-1])        

def GoldenRock():
    Lg=["1. DR.MALAS HOSPITAL","2.GKM HOSPITAL","3.SINDUJA HOSPITAL","4.MARUTI HOSPITAL","5.SRI KUMARAN HOSPITAL","6.VELAN SPECIALITY HOSPITALS PVT HOSPITAL"]
    for i in Lg:
        print(i)
    hno=int(input("Enter the hospital no. chosen"))
    return(Lg[hno-1])


